# Default virtual host — localhost
<VirtualHost *:80>
    ServerName localhost
    DocumentRoot /usr/local/apache2/htdocs

    <Directory /usr/local/apache2/htdocs>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

# Test site — www.mojefirma.cz
# Add "127.0.0.1 www.mojefirma.cz" to your /etc/hosts to use this
<VirtualHost *:80>
    ServerName www.mojefirma.cz
    DocumentRoot /usr/local/apache2/htdocs/mojefirma

    <Directory /usr/local/apache2/htdocs/mojefirma>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

# Test site — www.example.cz
# Add "127.0.0.1 www.example.cz" to your /etc/hosts to use this
<VirtualHost *:80>
    ServerName www.example.cz
    DocumentRoot /usr/local/apache2/htdocs/example

    <Directory /usr/local/apache2/htdocs/example>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

# AUTO-GENERATED: lagouch111.cz
<VirtualHost *:80>
    ServerName lagouch111.cz
    DocumentRoot /usr/local/apache2/htdocs/lagouch111.cz

    <Directory /usr/local/apache2/htdocs/lagouch111.cz>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

# AUTO-GENERATED: hesdkfsdof.com
<VirtualHost *:80>
    ServerName hesdkfsdof.com
    DocumentRoot /usr/local/apache2/htdocs/hesdkfsdof.com

    <Directory /usr/local/apache2/htdocs/hesdkfsdof.com>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

# AUTO-GENERATED: sdfsadss.cz
<VirtualHost *:80>
    ServerName sdfsadss.cz
    DocumentRoot /usr/local/apache2/htdocs/sdfsadss.cz

    <Directory /usr/local/apache2/htdocs/sdfsadss.cz>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

# AUTO-GENERATED: sdfass.cz
<VirtualHost *:80>
    ServerName sdfass.cz
    DocumentRoot /usr/local/apache2/htdocs/sdfass.cz

    <Directory /usr/local/apache2/htdocs/sdfass.cz>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>


# AUTO-GENERATED: aaasdasd.cz
<VirtualHost *:80>
    ServerName aaasdasd.cz
    DocumentRoot /usr/local/apache2/htdocs/aaasdasd.cz

    <Directory /usr/local/apache2/htdocs/aaasdasd.cz>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>



# AUTO-GENERATED: sdfsdf.cz
<VirtualHost *:80>
    ServerName sdfsdf.cz
    DocumentRoot /usr/local/apache2/htdocs/sdfsdf.cz

    <Directory /usr/local/apache2/htdocs/sdfsdf.cz>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

