# Default virtual host — localhost
<VirtualHost *:80>
    ServerName localhost
    DocumentRoot /usr/local/apache2/htdocs

    <Directory /usr/local/apache2/htdocs>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

# Test site — www.mojefirma.cz
# Add "127.0.0.1 www.mojefirma.cz" to your /etc/hosts to use this
<VirtualHost *:80>
    ServerName www.mojefirma.cz
    DocumentRoot /usr/local/apache2/htdocs/mojefirma

    <Directory /usr/local/apache2/htdocs/mojefirma>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

# Test site — www.example.cz
# Add "127.0.0.1 www.example.cz" to your /etc/hosts to use this
<VirtualHost *:80>
    ServerName www.example.cz
    DocumentRoot /usr/local/apache2/htdocs/example

    <Directory /usr/local/apache2/htdocs/example>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>


















# AUTO-GENERATED: 234lagouch123.cz
<VirtualHost *:80>
    ServerName 234lagouch123.cz
    DocumentRoot /usr/local/apache2/htdocs/234lagouch123.cz

    <Directory /usr/local/apache2/htdocs/234lagouch123.cz>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>



# AUTO-GENERATED: firstdomain.com
<VirtualHost *:80>
    ServerName firstdomain.com
    DocumentRoot /usr/local/apache2/htdocs/firstdomain.com

    <Directory /usr/local/apache2/htdocs/firstdomain.com>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

